// Run: node scripts/gen-chart.mjs  ->  src/components/chartGeometry.js
// Generates the static hero chart geometry (coast, depth bands, contours, soundings).
// Seeded, so re-running gives identical output.
let seed = 20241;
const rnd = () => (seed = (seed * 16807) % 2147483647) / 2147483647;

const W = 560, H = 640;
const A = [90, -110], B = [750, 550]; // base coast line, extended past the viewBox
const len = Math.hypot(B[0] - A[0], B[1] - A[1]);
const dir = [(B[0] - A[0]) / len, (B[1] - A[1]) / len];
const n = [-dir[1], dir[0]]; // points to the sea (bottom-left)

const wobble = (amp) => {
  const ph = [0, 0, 0, 0].map(() => rnd() * Math.PI * 2);
  return (t) => amp * (0.5 * Math.sin(t * 9 + ph[0]) + 0.25 * Math.sin(t * 23 + ph[1]) + 0.15 * Math.sin(t * 51 + ph[2]) + 0.1 * Math.sin(t * 97 + ph[3]));
};

const curve = (offset, amp, steps = 90) => {
  const w = wobble(amp);
  return Array.from({ length: steps + 1 }, (_, i) => {
    const t = i / steps;
    const d = offset + w(t);
    return [A[0] + (B[0] - A[0]) * t + n[0] * d, A[1] + (B[1] - A[1]) * t + n[1] * d];
  });
};

const r = (v) => Math.round(v * 10) / 10;
const toPath = (pts) => "M" + pts.map(([x, y]) => `${r(x)} ${r(y)}`).join("L");
// Close a curve on the land side via a far corner outside the viewBox.
const toArea = (pts) => toPath(pts) + `L${W + 400} ${-400}Z`;

const coast = curve(0, 16, 140);
const c5 = curve(38, 12);
const c10 = curve(92, 16);
const c20 = curve(176, 20);
const c50 = curve(300, 24);

const depthAt = ([x, y]) => (x - A[0]) * n[0] + (y - A[1]) * n[1];
const inside = ([x, y], m = 18) => x > m && x < W - m && y > m && y < H - m;

// Contour depth labels sit on their line at a fixed t.
const labelAt = (pts, t) => pts[Math.round(t * (pts.length - 1))].map(r);
const labels = [labelAt(c5, 0.58), labelAt(c10, 0.66), labelAt(c20, 0.56), labelAt(c50, 0.64)];

// Ship's track: straight legs between position fixes (kept in sync with chart.jsx).
const track = [[40, 640], [70, 600], [158, 476], [262, 340], [326, 258]];
const segDist = (p, a, b) => {
  const [dx, dy] = [b[0] - a[0], b[1] - a[1]];
  const t = Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy)));
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
};
const nearTrack = (p) => track.slice(1).some((b, i) => segDist(p, track[i], b) < 26);

// Soundings: deeper numbers further from the coast, like a real chart.
const soundings = [];
for (let tries = 0; soundings.length < 20 && tries < 6000; tries++) {
  const p = [rnd() * W, rnd() * H];
  const d = depthAt(p);
  if (d < 14 || !inside(p) || soundings.some((s) => Math.hypot(s.x - p[0], s.y - p[1]) < 54)) continue;
  if (Math.hypot(p[0] - 104, p[1] - 404) < 84 || nearTrack(p)) continue; // compass rose, track
  if (labels.some((l) => Math.hypot(l[0] - p[0], l[1] - p[1]) < 40)) continue; // contour labels
  if (p[0] > W * 0.6 && p[1] < H * 0.42) continue; // portrait inset sits here
  const depth = Math.max(1, Math.round(d / 9 + rnd() * 2));
  soundings.push({ x: r(p[0]), y: r(p[1]), v: depth });
}

const geometry = {
  land: toArea(coast),
  coast: toPath(coast),
  shoal: toArea(c5),
  shallow: toArea(c10),
  sea: toArea(c20),
  contours: [
    { d: toPath(c5), label: "5", at: labels[0] },
    { d: toPath(c10), label: "10", at: labels[1] },
    { d: toPath(c20), label: "20", at: labels[2] },
    { d: toPath(c50), label: "30", at: labels[3] },
  ],
  soundings,
};

const { writeFileSync } = await import("node:fs");
writeFileSync(
  new URL("../src/components/chartGeometry.js", import.meta.url),
  `// Generated by scripts/gen-chart.mjs (seeded). Re-run it instead of editing by hand.\nexport const geometry = ${JSON.stringify(geometry)};\n`,
);
